# Site settings
title: HuXiMi Blog
SEOTitle: 胡小米的博客 | HuXiMi Blog
header-img: img/home-bg.jpg
email: admin@huximi.com
description: "关于胡小米的成长历程 | 这里是 @HuXiMi胡小米 的个人博客，与你一起发现更大的世界。"
keyword: "胡小米, HuXiMi胡小米,胡小米的博客, HuXiMi Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: "https://www.huximi.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    huximi
twitter_username:   huximi
facebook_username:  Ximi Hu
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
#disqus_username: hux

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huximi.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "浅浅秋色，念念芳华"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "沈健的技术博客",
        href: "https://shenjian.online/archives"
     },{
        title: "黄玄的博客",
        href: "https://huangxuan.me"
    },{
      title: "Logo通过DesignEvo设计制作",
      href: "https://www.designevo.com/cn/logo-maker/"
    }
]
